 
path:
    logs: "logs"
    log_config: "configs/logging.yml"
    c: "C:/myfolder/myopenfoamfolder"
    e: "E:/afolder/afolder/mykingdomforafolder"
    server: "//server.location/myfolder/myfolder"
    fig: "C:/myfolder/storeFiguresHere"