# Please copy this template to config.yml then set your
# preferred file locations below.
---

path:
    logs: "logs"
    log_config: "configs/logging.yml"
    c: "C:/myfolder/myopenfoamfolder"
    e: "E:/afolder/afolder/mykingdomforafolder"
    server: "//server.location/myfolder/myfolder"
    fig: "C:/myfolder/storeFiguresHere"
    slurmFolder: '/working/myusername'
    legend_units: "myfolder/legend_units.csv"
timing:
    abort1: 120
    abort2: 60
    
---